branches:
  # enable all branches, gh-pages branch is disabled by default
  only:
    - gh-pages
    - /.*/

sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:v0.4.7

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/script.sh

matrix:
  fast_finish: true
